BoxLayout:

    orientation: 'vertical'
#   orientation: 'horizontal'
    Button:
        id: added_number
        text: 'Clear'
        on_press: app.clear_fields()
    TextInput:
        id: input_name
        text: ''
    Button:
        id: output_label
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        text: 'Enter your name'
        color: (1, 1, 0, 1)
